// ── Constantes e definição de ferramentas (desktop) ───────
const CARGOS={diretoria:'Diretoria',gerente_garagem:'Gerente de Garagem',gerente_operacional:'Gerente Operacional',coordenador:'Coordenador',supervisor:'Supervisor',lider_pcm:'Líder PCM',assistente_pcm:'Assistente PCM',almoxarifado:'Almoxarifado',lider_almoxarifado:'Líder Almoxarifado',lider_operacional:'Líder Operacional',lider_suprimentos:'Líder de Suprimentos',operacoes_seguras:'Operações Seguras',lider_oficina:'Líder de Oficina',lider_patio:'Líder de Pátio',lavador:'Lavador',manobrista:'Manobrista',frentista:'Frentista',plantao:'Plantão'};

const ST_CFG={disponivel:{l:'Disponível',cls:'b-disp'},em_linha:{l:'Em Linha',cls:'b-linha'},manutencao:{l:'Manutenção',cls:'b-manut'},aguardando_peca:{l:'Ag. Peça',cls:'b-agpeca'},sinistro:{l:'Sinistro',cls:'b-sinistro'}};

const FERRAMENTAS_DEF=[
  {id:'ferr-prev', icon:'🔩', nome:'Painel Preventivas',
    executa:  ['lider_pcm','assistente_pcm'],
    valida:   ['lider_pcm'],
    visualiza:['gerente_garagem','diretoria','lider_oficina'],
  },
  {id:'ferr-pcm', icon:'🔧', nome:'Painel PCM',
    executa:  ['lider_pcm','assistente_pcm'],
    valida:   ['lider_pcm'],
    visualiza:['gerente_garagem','diretoria','lider_oficina'],
  },
  {id:'ferr-210', icon:'📋', nome:'2.10 Soltura de Frota',
    executa:  ['lider_patio'],
    valida:   ['lider_patio'],
    visualiza:['lider_operacional','gerente_garagem','diretoria','lider_pcm','assistente_pcm'],
  },
  {id:'ferr-22',  icon:'🔧', nome:'Painel do Manutentor',
    executa:  ['lider_oficina','lider_pcm','assistente_pcm'],
    valida:   ['lider_pcm'],
    visualiza:['gerente_garagem','diretoria','assistente_pcm'],
  },
  {id:'ferr-21',  icon:'📋', nome:'2.1 Fechamento Garagem',
    executa:  ['supervisor','coordenador','gerente_operacional','lider_operacional','lider_patio','lider_pcm','lider_oficina','almoxarifado','lider_almoxarifado','lider_suprimentos'],
    valida:   ['gerente_garagem'],
    visualiza:['diretoria','operacoes_seguras'],
  },
  {id:'ferr-26',  icon:'💰', nome:'2.6 Previsibilidade',
    executa:  ['lider_pcm','assistente_pcm'],
    valida:   ['lider_pcm'],
    visualiza:['gerente_garagem','diretoria','operacoes_seguras'],
  },
  {id:'ferr-218', icon:'🆘', nome:'2.18 SOS Recolha Anormal',
    executa:  ['assistente_pcm','lider_pcm'],
    valida:   ['lider_pcm','coordenador','supervisor'],
    visualiza:['gerente_garagem','diretoria','lider_operacional','lider_patio','lider_oficina'],
  },
  {id:'ferr-lav', icon:'🧼', nome:'3.2 Checklist Lavagem',
    executa:  ['lavador'],
    valida:   ['lider_patio'],
    visualiza:['lider_operacional','gerente_garagem','diretoria'],
  },
  {id:'ferr-lav-lavador', icon:'🚿', nome:'Minha Lista de Lavagem',
    executa:  ['lavador'],
    valida:   [],
    visualiza:[],
  },
  {id:'ferr-ctrl', icon:'✅', nome:'Controle Soltura',
    executa:  ['lider_patio'],
    valida:   [],
    visualiza:['lider_operacional','gerente_garagem','diretoria'],
  },
  {id:'ferr-almox', icon:'📦', nome:'Kits / Valetamento',
    executa:  ['almoxarifado','lider_suprimentos'],
    valida:   ['lider_almoxarifado'],
    visualiza:['lider_pcm','assistente_pcm','lider_oficina','gerente_garagem','diretoria'],
  },
  {id:'ferr-almox-inv', icon:'📋', nome:'Inventários',
    executa:  ['almoxarifado','lider_almoxarifado','lider_suprimentos'],
    valida:   ['lider_almoxarifado'],
    visualiza:['lider_pcm','assistente_pcm','gerente_garagem','diretoria'],
  },
  {id:'ferr-almox-wms', icon:'🗂️', nome:'WMS — Catálogo',
    executa:  ['almoxarifado','lider_almoxarifado','lider_suprimentos'],
    valida:   ['lider_almoxarifado'],
    visualiza:['lider_pcm','assistente_pcm','gerente_garagem','diretoria'],
  },
  {id:'ferr-almox-painel', icon:'📊', nome:'Painel do Líder',
    executa:  ['lider_almoxarifado','lider_suprimentos'],
    valida:   ['lider_almoxarifado'],
    visualiza:['lider_pcm','assistente_pcm','gerente_garagem','diretoria'],
  },
  {id:'ferr-almox-compras', icon:'🛒', nome:'Pedidos de Compra',
    executa:  ['almoxarifado','lider_almoxarifado','lider_suprimentos'],
    valida:   ['lider_suprimentos'],
    visualiza:['lider_pcm','assistente_pcm','gerente_garagem','diretoria'],
  },
  {id:'ferr-33', icon:'👣', nome:'3.3 Ronda Operacional',
    executa:  ['lider_pcm','lider_oficina','almoxarifado','lider_almoxarifado','lider_suprimentos','lider_patio','lider_operacional'],
    valida:   ['supervisor','coordenador'],
    visualiza:['gerente_garagem','diretoria','operacoes_seguras'],
  },
  {id:'ferr-211', icon:'🔴', nome:'2.11 Carros Indisponíveis',
    executa:  [],
    valida:   [],
    visualiza:['lider_patio','lider_pcm','assistente_pcm','lider_oficina','lider_operacional','gerente_garagem','diretoria'],
  },
  {id:'ferr-212', icon:'📊', nome:'2.12 Indicadores Técnicos',
    executa:  [],
    valida:   [],
    visualiza:['lider_pcm','assistente_pcm','lider_operacional','gerente_garagem','diretoria'],
  },
  {id:'ferr-lubri', icon:'🛢️', nome:'Relatório Lubrificação',
    executa:  ['lubrificador'],
    valida:   [],
    visualiza:['gerente_garagem','diretoria','coordenador','supervisor','lider_operacional','lider_pcm'],
  },
  {id:'ferr-pecas', icon:'🔩', nome:'Peças & Compras',
    executa:  ['almoxarifado','lider_almoxarifado','lider_suprimentos'],
    valida:   ['lider_suprimentos'],
    visualiza:['lider_pcm','assistente_pcm','lider_oficina','gerente_garagem','diretoria'],
  },
];

const PAPEIS=['executa','valida','visualiza'];
const PAPEL_CFG={
  executa:  {ic:'▶',l:'Executa', c:'#3B82F6', bg:'#3B82F618', border:'#3B82F640'},
  valida:   {ic:'✓',l:'Valida',  c:'#F59E0B', bg:'#F59E0B18', border:'#F59E0B40'},
  visualiza:{ic:'👁',l:'Visualiza',c:'#00C48C',bg:'#00C48C18',border:'#00C48C40'},
};
